config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'

  get '/about',     to: 'static_pages#about'

  get '/players',     to: 'players#index'
  get '/sports',      to: 'sports#index'
  get '/teams',       to: 'teams#index'
  get '/search',      to: 'sports#index'
 
  resources  :teams
  resources  :players
  resources  :users,  except: [:new]
  resources :sessions, only: [:create]

  get '/signup',      to:  'users#new'
  get '/signin',      to:  'sessions#new'
  delete '/signout',  to:  'sessions#destroy' 

end

app/models/player.rb
class Player < ActiveRecord::Base
  belongs_to :team
  has_many :subordinates, class_name: 'Player', foreign_key: 'team_id'

  # belongs_to :user
  # validates :full_name, presence:true, length { minimum: 3, maximum: 254 }
end

app/models/sport.rb
class Sport < ActiveRecord::Base
  has_many :teams
end

app/models/team.rb
class Team < ActiveRecord::Base
  belongs_to :sport
  has_many :subordinates, class_name: 'Team', foreign_key: 'sport_id'

  
end

app/models/user.rb
class User < ActiveRecord::Base
  before_save { email.downcase! }
  has_many :players

  validates :name, presence: true, length: { minimum: 3, maximum: 254 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(?:\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 254 },
            format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
  has_secure_password

  def self.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def self.digest(token)
    Digest::SHA1.hexdigest(token.to_s)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  # before_action :set_item, only: [:show, :edit, :update, :destory]
  # before_action :signed_in_user, except: [:index, :show]
  # before_action :correct_user, except: [:new, :create, :index, :show]

  def index
  end

  def show
    response = HTTParty.get "http://api.usatoday.com/open/salaries/nba?players=&encoding=json&api_key=rsf229wnbzyeq3cf4y6wqrfg"
    @data = JSON.parse(response.body)
  
    @salaries_object = @data["salaries"][0]
    @salaries = @salaries_object["salary"]
  end

  def new
  end

  def create
    @player = current_user.players.new(player_params)
    if @player.save
      flash[:success] = 'Player created.'
      redirect_to players_path
    else
     render 'new'  
    end
  end  

def edit
end


end
  

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :redirect_if_signed_in, except: [:destroy]

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      sign_in user
      redirect_to user_path user_path
    else
      flash.new[:danger] = "You have entered an invalid email/password combination"
      render 'new'
    end
  end
  
  def destroy
    sign_out
    redirect_to root_path
  end  

end

app/controllers/sports_controller.rb
class SportsController < ApplicationController
 
  def index
    response = HTTParty.get "http://api.usatoday.com/open/salaries/#{params[:sport]}?players=&encoding=json&api_key=rsf229wnbzyeq3cf4y6wqrfg"
    @data = JSON.parse(response.body)

    @salaries_object = @data["salaries"][0]
    @salaries = @salaries_object["salary"]
    @teams = []
    @teams_hash = Hash.new()
    @teams_hash_obj = Hash.new()

    @salaries.each do |salary| 
      @teams_hash[salary['team_full_name']] = salary['team_last_name']
      @team = Team.new(name: salary['team_full_name'], fullname: salary['team_last_name'])
      unless @teams.include?(@team)
        @teams.push(@team)
        @teams_hash_obj[salary['team_full_name']] = @team
      end
    end
    
    puts @teams_hash
    puts @teams_hash_obj
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  
  end

  def about

  end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController

  def index
    response = HTTParty.get "http://api.usatoday.com/open/salaries/nba?players=&encoding=json&api_key=rsf229wnbzyeq3cf4y6wqrfg"
    @data = JSON.parse(response.body)
  
    @salaries_object = @data["salaries"][0]
    @salaries = @salaries_object["salary"]
    @teams = []
    @teams_hash = Hash.new()
    @teams_hash_obj = Hash.new()

    @salaries.each do |salary| 
      @teams_hash[salary['team_full_name']] = salary['team_last_name']
      @team = Team.new(name: salary['team_full_name'], fullname: salary['team_last_name'])
      unless @teams.include?(@team)
        @teams.push(@team)
        @teams_hash_obj[salary['team_full_name']] = @team
      end
    end
    puts @teams_hash
    puts @teams_hash_obj
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :signed_in_user,  only: [:edit, :udate, :destroy]
  before_action :correct_user,  only: [:edit, :update]
  before_action :redirect_if_signed_in, only: [:new, :create]
  before_action :admin_user, only: [:destroy]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      sign_in @user
      flash[:success] = "Welcome"
      redirect_to user_path @user
    else
      render 'new'  
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def index
    @users = User.all
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = 'Profile updated.'
      redirect_to user_path @user
    else
      render 'edit'  
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:success] = 'User account deleted.'
    redirect_to root_path
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_path) unless current_user?(@user)
  end
  
end  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    remember_taken = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.digest(remember_token))
    self.current_user = user
  end

  def sign_out
    current_user.update_attribute(:remember_token, User.digest(User.new_remember_token))
    cookies.delete(:remember_token)
    self.current_user = nil
  end

  def signed_in?
    !current_user.nil?
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    remember_token = User.digest(cookies[:remember_token])
    @current_user ||=User.find_by(remember_token: remember_token)
  end

  def current_user?(user)
    current_user == user  
  end  

  def redirect_if_signed_in
    redirect_to(root_path) if signed_in?
  end

  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end

  def store_location
    session[:return_to] = request.url if request.get?
  end

  def signed_in_user
    unless signed_in?
      flash[:warning] = "Please sign in"
      redirect_to signin_url
    end
  end

  def admin_user
    redirect_to(root_path) unless current_user.admin?
  end
end

app/helpers/sports_helper.rb
module SportsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
 <section class="container">

  <!-- Static navbar -->
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button"
                class="navbar-toggle collapsed"
                data-toggle="collapse"
                data-target="#navbar"
                aria-expanded="false"
                aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      </div>
      <div id="navbar" class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
          <li <%= 'class="active"' if @active == 'home'  %>><a href="/">Home</a></li>
          <li <%= 'class="active"' if @active == 'items' %>><a href="/teams">Teams</a></li>
          <li <%= 'class="active"' if @active == 'about' %>><a href="/about">About</a></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Players", players_path %></li>
          <li><%= link_to "New Player", new_player_path %></li>
          <% if signed_in? %>
            <li><%= link_to "My Profile", user_path(current_user) %></li>
            <li><%= link_to "Edit Profile", edit_user_path(current_user) %></li>
            <li><%= link_to "Sign Out", signout_path, method: 'delete' %></li>
          <% else %>
            <li><%= link_to "Sign Up", signup_path %></li>
            <li><%= link_to "Sign In", signin_path %></li>
          <% end %>
        </ul>
      </div><!--/.nav-collapse -->
    </div><!--/.container-fluid -->
  </nav>

</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Sport$ | <%= yield(:title) %></title>

   <!-- Bootstrap -->
    <link href="css/bootstrap.min.css" rel="stylesheet">
  
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= debug(params) if Rails.env.development? %>

  <%= render 'layouts/header' %> 
  <div class='container-fluid>'
  <% flash.each do |key, value| %>
    <%= content_tag(:div, value, class: "alert alert-#{key} no-margin") %>
  <% end %>
  <%= yield %>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="js/bootstrap.min.js"></script>
</body>
</html>

app/views/players/_fields.html.erb
<%= form_for(@player) do |f| %>
  <%+ render 'shared/error_messages', object: f.object %>

  <%= f.label :player_full_name %>
  <%= f.text.field :player_full_name, autofocus: true %>

  <br>
  <%= f.submit 'Save' %>
  <% end %>

app/views/players/edit.html.erb
<% provide(:title, 'Edit') %>
<h1> Edit Player Selection </h1>

<%= render 'players/fields' %>

app/views/players/index.html.erb
<% provide(:title, 'Players Index') %>
<h1>Players</h1>

<h2> Count:<%= @salaries.count %></h2>

<!-- <h2>first_salary<%= @first_salary %></h2>
<h2>Salary_2<%= @second_salary %></h2>
<h2>Salary_3<%= @third_salary %></h2>
 -->
  <% @salaries.each do |salary| %>
      <ul>
        <li>
          <%= link_to salary["player_full_name"] %> | 
          <%= link_to 'delete', player, method: :delete, data: { confirm: 'Are you sure?' } %>
        </li>
      <% end %>
    </ul>  

app/views/players/new.html.erb
<% provide(:title, 'Add') %>
<h1> Add Player Selection </h1>

<%= render 'players/fields' %>

app/views/players/show.html.erb
<% provide(:title, @player.name) %>
<h1> @player.name </h1>

<h4>Member: <%= link_to @player.user.name, user_paty(@player.user) %></h4>

<!-- <dt> Player: </dt>
<dd><%= player.name %></dd>
<dt> Team: </dt>
<dd><%= team_full_name %></dd>
<dt> Salary: </dt>
<dd><%= salary %></dd> -->

app/views/shared/_error_messages.html.erb
  <% if object.errors.any? %>
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
      <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>   

app/views/sport/index.html.erb
<% provide(:title, 'Sports Index') %>
<h1>Sport Leagues</h1>

<ul>
  <% @sports.each do |sport| %>
    <li>
      <%= link_to sport.name, sport_path(sport.id) %> | 
    </li>
  <% end %>
</ul>

app/views/sports/index.html.erb
<% provide(:title, 'Sports Index') %>
<h1>Sports</h1>

<h2>Team count:<%= @teams_hash.length %></h2>

  <% @teams_hash_obj.each do |team| %>
    <li>
      <% @local_team = team[1] %> 
      <%= link_to team_path(@local_team.fullname)  %> 
    </li>
  <% end %>

app/views/static_pages/about.html.erb
<% provide(:title, 'About') %>
<h1> Sport$ Salaries</h1>
<p> is a <a href= 'https://generalassemb.ly/' 'target=_blank'> General Assembly</a> project of Beth Laing, cohort 2, Atlanta.  </p>

app/views/static_pages/home.html.erb
<% provide(:title, 'Home') %>
<h1> Sport$ Salaries</h1>
<p> Sport$ was created to easily evaluate and compare the highest paid athletes for major sports leagues. </p>

<ul>
  Select the sport league you want to explore:

  <li> NBA | Basketball </li>
  <li><%= link_to 'NBA | Basketball', '/search?sport=nba' %></li>
  <li> MLB | Baseball </li>
  <li> NHL |  Hockey </li>
  <li> NFL |  Football </li>
</ul>  

app/views/users/_fields.html.erb
<% form_for(@user) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>

  <%= f.label :name %>
  <%= f.text_field :name, autofocus: true %>
  
  <br>
  <%= f.label :email %>
  <%= f.text_field :email %>

  <br>
  <%= f.label :password %>
  <%= f.password_field :password %>

  <br>
  <%= f.label :password_confirmation, "Confirm password" %>
  <%= f.password_field :password_confirmation %>
  <br>
  <%= f.submit 'Save' %>
<% end %>

app/views/users/edit.html.erb
<% provide(:title, 'Edit'Profile) %>
<h1> Edit Profile </h1>

<%= render 'users/fields' %>

app/views/users/index.html.erb
<% provide(:title, 'All Users') %>
<h1>All Users</h1>


<ul>
  <% @users.each do |user| %>
    <li>
      <%= link_to user.name, user_path(user.id) %> 
      <% if current_user.admin?  && !current_user?(user) %>
      | <%= link_to "delete", user, method: :delete, data: { confirm: 'Are you sure?' } %>
      <% end %>
    </li>
  <% end %>
</ul>  

app/views/users/new.html.erb
<% provide(:title, 'Sign Up') %>
<h1> Sign Up </h1>

<% render 'users/fields' %>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>

<h1><%= @user.name %></h1>

<h4>Players Added: </h4>
<ul>
  <% @usesr.players.each do |player| %>
    <li>
      <%= link_to player.name, player_path(player) %>
      <%= if current_user?(@user) %>
          | <%= link_to "edit", edit_player_path(player) %>
      <% end %>    
    </li>
  <% end %>
</ul> 